#ifndef INTERFACERESTAPI_GLOBAL_H
#define INTERFACERESTAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERFACERESTAPI_LIBRARY)
#  define INTERFACERESTAPI_EXPORT Q_DECL_EXPORT
#else
#  define INTERFACERESTAPI_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERFACERESTAPI_GLOBAL_H
